### PR TITLE
Fixed formating so all cultures have a point in the priority instead of comma

### PR DESCRIPTION
**Pull request by hansterwal**
- Fixed formating so all cultures have a point in the priority, inste…
…ad of a comma.

- if no last modifieddate available don't show it.
- Changed formating of modified to date only see: https://www.internetmarketingninjas.com/blog/search-engine-optimization/the-ultimate-guide-to-xml-sitemaps/

### CODE REVIEW

**Review by CorteXodus — COMMENTED** [review]
I think I understand what you're up to with these changes, but I actually do need the time and offset in the date/time information for these nodes in my implementation.

**Review by CorteXodus — COMMENTED** [review]
I'm curious what the benefit to this modification is. Can you elaborate on the change?

**Comment by hansterwal** [comment]
Basically I needed a check on the datetime part so, when sitecore returns a minvalue date (0001-01-01) it doesn't get pushed into the output xml, otherwise google webmaster tools gives you a parsing error.

The priority needs to be with a point, depending on your culture you can end up with a comma (which is invalid), by setting an invariant culture you will always end up with a comma.

The time part is optional, our seo specialist found in nicer without, but I can ammend it with?

**Comment by codetwiddler** [comment]
I wasn't aware of the google parsing error.

Wow, ok, I didn't know about the comma thing but, it makes sense. Our implementation doesn't do any culture-changes so I didn't consider that. 

If you would amend it to continue using the time component, that would be great.

Thanks for your input, this is stuff I didn't know about!

**Comment by hansterwal** [comment]
Hi, 

I made an ammend to include the time part.

**Review by codetwiddler — APPROVED** [review]

**Pull request merged**
